version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: scouts-db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-scouts}
      POSTGRES_USER: ${POSTGRES_USER:-scouts}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-scouts}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
