export const newPlayer1: Player = {
  name: "Dudu",
  attacks: {
    sharkAttack: 0,
    parallel: 0,
    halfBottom: 0,
    longDiagonal: 0,
    shortDiagonal: 0,
    halfDrop: 0,
    dropBack: 0,
    block: 0,
    ace: 0,
    forFree: 0,
  },
  errors: {
    attack: 0,
    defense: 0,
    netTouch: 0,
    serve: 0,
    set: 0,
  },
};
export const newPlayer2: Player = {
  name: "Arthur",
  attacks: {
    sharkAttack: 0,
    parallel: 0,
    halfBottom: 0,
    longDiagonal: 0,
    shortDiagonal: 0,
    halfDrop: 0,
    dropBack: 0,
    block: 0,
    ace: 0,
    forFree: 0,
  },
  errors: {
    attack: 0,
    defense: 0,
    netTouch: 0,
    serve: 0,
    set: 0,
  },
};
export const newPlayer3: Player = {
  name: "Gui",
  attacks: {
    sharkAttack: 0,
    parallel: 0,
    halfBottom: 0,
    longDiagonal: 0,
    shortDiagonal: 0,
    halfDrop: 0,
    dropBack: 0,
    block: 0,
    ace: 0,
    forFree: 0,
  },
  errors: {
    attack: 0,
    defense: 0,
    netTouch: 0,
    serve: 0,
    set: 0,
  },
};
export const newPlayer4: Player = {
  name: "Tavinho",
  attacks: {
    sharkAttack: 0,
    parallel: 0,
    halfBottom: 0,
    longDiagonal: 0,
    shortDiagonal: 0,
    halfDrop: 0,
    dropBack: 0,
    block: 0,
    ace: 0,
    forFree: 0,
  },
  errors: {
    attack: 0,
    defense: 0,
    netTouch: 0,
    serve: 0,
    set: 0,
  },
};
