export const newPlayer1: Player = {
  name: "Dudu",
  attacks: {
    sharkAttack: 3,
    sharkAttackAttempts: 3,
    parallel: 1,
    parallelAttempts: 2,
    halfBottom: 2,
    halfBottomAttempts: 2,
    longDiagonal: 2,
    longDiagonalAttempts: 2,
    shortDiagonal: 1,
    shortDiagonalAttempts: 1,
    halfDrop: 0,
    halfDropAttempts: 0,
    dropBack: 1,
    dropBackAttempts: 1,
    block: 0,
    blockAttempts: 0,
    forFree: 0,
    forFreeAttempts: 1,
    ace: 0,
  },
  errors: {
    attack: 3,
    defense: 1,
    netTouch: 1,
    serve: 0,
    set: 1,
    receive: 0,
  },
};
export const newPlayer2: Player = {
  name: "Arthur",
  attacks: {
    sharkAttack: 4,
    sharkAttackAttempts: 8,
    parallel: 1,
    parallelAttempts: 2,
    halfBottom: 0,
    halfBottomAttempts: 0,
    longDiagonal: 1,
    longDiagonalAttempts: 1,
    shortDiagonal: 0,
    shortDiagonalAttempts: 0,
    halfDrop: 0,
    halfDropAttempts: 1,
    dropBack: 0,
    dropBackAttempts: 0,
    block: 0,
    blockAttempts: 0,
    forFree: 0,
    forFreeAttempts: 2,
    ace: 0,
  },
  errors: {
    attack: 1,
    defense: 5,
    netTouch: 0,
    serve: 1,
    set: 1,
    receive: 0,
  },
};
export const newPlayer3: Player = {
  name: "Gui",
  attacks: {
    sharkAttack: 6,
    sharkAttackAttempts: 12,
    parallel: 0,
    parallelAttempts: 1,
    halfBottom: 0,
    halfBottomAttempts: 1,
    longDiagonal: 0,
    longDiagonalAttempts: 0,
    shortDiagonal: 0,
    shortDiagonalAttempts: 0,
    halfDrop: 1,
    halfDropAttempts: 1,
    dropBack: 1,
    dropBackAttempts: 1,
    block: 2,
    blockAttempts: 2,
    forFree: 0,
    forFreeAttempts: 0,
    ace: 0,
  },
  errors: {
    attack: 1,
    defense: 6,
    netTouch: 0,
    serve: 0,
    set: 0,
    receive: 0,
  },
};
export const newPlayer4: Player = {
  name: "Tavinho",
  attacks: {
    sharkAttack: 0,
    sharkAttackAttempts: 0,
    parallel: 1,
    parallelAttempts: 1,
    halfBottom: 1,
    halfBottomAttempts: 1,
    longDiagonal: 0,
    longDiagonalAttempts: 0,
    shortDiagonal: 2,
    shortDiagonalAttempts: 2,
    halfDrop: 0,
    halfDropAttempts: 0,
    dropBack: 0,
    dropBackAttempts: 1,
    block: 0,
    blockAttempts: 0,
    forFree: 0,
    forFreeAttempts: 0,
    ace: 0,
  },
  errors: {
    attack: 0,
    defense: 2,
    netTouch: 1,
    serve: 0,
    set: 1,
    receive: 0,
  },
};
